version: 2.1

jobs:
  build-and-test:
    docker:
      - image: circleci/openjdk:17-jdk-buster
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-
      - run: ./gradlew test
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
      - store_test_results:
          path: build/test-results/test/

  publish-docker-image:
    docker:
      - image: circleci/openjdk:17-jdk-buster
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build and Push Docker Image with Jib
          command: |
            if [ "${CIRCLE_BRANCH}" == "main" ]; then
              ./gradlew jib -Djib.to.image=erikasmu/weather-service:latest -Djib.to.auth.username=$DOCKERHUB_USERNAME -Djib.to.auth.password=$DOCKERHUB_PASS
            fi

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-and-test
      - publish-docker-image:
          requires:
            - build-and-test
          filters:
            branches:
              only: main
